### ISSUE TITLE
Porting the config file from .yml to preciceDict

### ISSUE THREAD

**Issue by JulianSchl** [precice/mbdyn-adapter#6]
Hi everyone,

trying to port the [precice-adapter-config.yml](https://github.com/precice/mbdyn-adapter/blob/master/tutorials/cavityFSI/fluid/precice-adapter-config.yml) to system/preciceDict, I was having the following issue after running pimpleFoam in the terminal:
```---[preciceAdapter] The preciceAdapter was loaded.
---[preciceAdapter] Reading preciceDict...
--> FOAM Warning : 
    From void adapterInfo(std::string, std::string)
    in file Utilities.C at line 50
    [31mError (deferred - will exit later) in the preCICE adapter: [0m
Entry 'readData' not found in dictionary "/home/julian/software/mbdyn-adapter/tutorials/cavityFSI/fluid/system/preciceDict.interfaces.Interface1"
```

It seems, that preCICE is expecting a `read` and a `write` parameter for every interface in the preciceDict. However, in the [precice-adapter-config.yml](https://github.com/precice/mbdyn-adapter/blob/master/tutorials/cavityFSI/fluid/precice-adapter-config.yml), there is only `read` or `write` defined for each interface.
Is there a way to either pass a empty `read` or `write` parameter via the preciceDict or is there another way to port this dict?

Please see my portet version of the preciceDict here:
  ```
  FoamFile
{
    version     2.0;
    format      ascii;
    class       dictionary;
    location    "system";
    object      preciceDict;
}

preciceConfig "../precice-config.xml";

participant Fluid_Solver;

modules (FSI);

interfaces
{
  Interface1
  {
    mesh              Fluid_CellCenters;
    patches           (bottomWall);
    locations         faceCenters;
    writeData
    (
    	Force
    );
  };
  Interface2
  {
    mesh              Fluid_Nodes;
    patches           (bottomWall);
    locations         faceNodes;
    readData
    (
        DisplacementDelta
    );
  };
};

FSI
{
  rho rho [1 -3 0 0 0 0 0] 1000;
}
```

**Comment by MakisH** [comment]
Hi @JulianSchl,

please add empty `readData();` and `writeData();`. Here is an example: https://github.com/precice/tutorials/blob/master/elastic-tube-3d/fluid-openfoam/system/preciceDict
